version: '3.8'

services:
  stationski-db:
    image: mysql:8.0
    container_name: stationski-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "sarah2025"
      MYSQL_DATABASE: stationSki
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - stationski-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psarah2025"]
      interval: 20s
      timeout: 20s
      retries: 40
      start_period: 180s

  stationski-app:
    build: .
    image: stationski-app
    container_name: stationski-app
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      stationski-db:
        condition: service_healthy
    networks:
      - stationski-net
    environment:
      SPRING_PROFILES_ACTIVE: dev

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - stationski-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      stationski-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - stationski-net

volumes:
  db_data:
  grafana_data:

networks:
  stationski-net:
