global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring_app:8087']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']